name: Build TimeInjector (x64)

on:
  push:
    branches: [ main, master ]
    paths:
      - 'TimeInjector/**'
      - '.github/workflows/build-timeinject-x64.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4

      - name: Setup MSVC (x64)
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Ensure Detours 4.0.1 (download)
        shell: cmd
        run: |
          if exist third_party\detours goto HAVE_DETOURS
          mkdir third_party
          cd third_party
          powershell -Command "Invoke-WebRequest -Uri https://github.com/microsoft/Detours/archive/refs/tags/v4.0.1.zip -OutFile detours.zip"
          powershell -Command "Expand-Archive detours.zip -DestinationPath ."
          ren Detours-4.0.1 detours
          del detours.zip
          :HAVE_DETOURS

      - name: Build Detours (x64)
        shell: cmd
        working-directory: ${{ github.workspace }}\third_party\detours\src
        run: |
          nmake clean || ver >nul
          nmake

      - name: Build TimeInjector DLL (x64)
        shell: cmd
        working-directory: ${{ github.workspace }}\TimeInjector
        run: |
          set CL=/nologo /O2 /MD /DNOMINMAX /DWIN32_LEAN_AND_MEAN
          set INCLUDES=/I %GITHUB_WORKSPACE%\third_party\detours\include
          set LIBS=/link /nologo /dll /def:exports.def /out:version.dll kernel32.lib user32.lib shlwapi.lib %GITHUB_WORKSPACE%\third_party\detours\lib.X64\detours.lib /NOIMPLIB
          cl TimeInjector.cpp %INCLUDES% %LIBS%

      - name: Upload artifact (x64)
        uses: actions/upload-artifact@v4
        with:
          name: TimeInjector-x64
          path: |
            ${{ github.workspace }}\TimeInjector\version.dll
            ${{ github.workspace }}\TimeInjector\timer.config

